; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Modules
projects[admin_menu][version] = "3.0-rc4"
projects[admin_menu][subdir] = "contrib"

projects[bootstrap_library][version] = "1.4"
projects[bootstrap_library][subdir] = "contrib"

projects[ctools][version] = "1.5"
projects[ctools][subdir] = "contrib"

projects[devel][version] = "1.5"
projects[devel][subdir] = "contrib"

projects[entity][version] = "1.5"
projects[entity][subdir] = "contrib"

projects[field_collection][version] = "1.0-beta8"
projects[field_collection][subdir] = "contrib"

projects[google_analytics][version] = "1.4"
projects[google_analytics][subdir] = "contrib"

projects[jquery_update][version] = "2.4"
projects[jquery_update][subdir] = "contrib"

projects[libraries][version] = "2.2"
projects[libraries][subdir] = "contrib"

projects[markdown][version] = "1.2"
projects[markdown][subdir] = "contrib"

projects[metatag][version] = "1.4"
projects[metatag][subdir] = "contrib"

projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = "contrib"

projects[ctools][version] = "1.4"
projects[ctools][subdir] = "contrib"

projects[stage_file_proxy][version] = "1.6"
projects[stage_file_proxy][subdir] = "contrib"

projects[token][version] = "1.5"
projects[token][subdir] = "contrib"

projects[views][version] = "3.8"
projects[views][subdir] = "contrib"

; Themes
projects[bootstrap][version] = "3.0"
projects[bootstrap][subdir] = "contrib"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[bootstrap_hollywood][download][type] = "local"
projects[bootstrap_hollywood][download][url] = "/lib/themes/hollywood/bootstrap_hollywood'"
projects[bootstrap_hollywood][type] = "theme"
projects[bootstrap_hollywood][subdir] = "hollywood"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
# libraries[bootstrap][download][type] = "git"
# libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip"
# libraries[bootstrap][directory_name] = "bootstrap"
# libraries[bootstrap][type] = "library"

